Integrate Flex Decoding
pytorch-labs/gpt-fast pull request #196
Opened 2024-08-21 03:29 UTC by BoyuanFeng

This PR integrates flex decoding with gpt-fast.

### End-to-end performance gain of Llama2-7b

Device: H100
Unit: tokens/sec

Length | spda | Flex Decoding | Speedup
-- | -- | -- | --
1024 | 143.57 | 142.59 | 0.99x
2048 | 138.67 | 140.13 | 1.01x
4096 | 128.85 | 135.31 | 1.05x
8192 | 111.59 | 125.38 | 1.12x
16384 | 89 | 109.8 | 1.23x
32768 | 64.11 | 87.67 | 1.37x

command:
```
export MODEL_REPO=meta-llama/Llama-2-7b-chat-hf
python generate.py --compile --max_new_tokens 16384 --checkpoint_path checkpoints/$MODEL_REPO/model.pth --prompt "Hello, my name is"
```

Please also set `ModelArgs.block_size = 65536` to repeat the result.

We expect to see larger speedup on longer context length.

2024-08-22 23:20 UTC, Chillee commented on model.py
> +    def _forward(self, mask: BlockMask, idx: Tensor, input_pos: Optional[Tensor] = None) -> Tensor:
Why was this refactor done?

2024-08-22 23:20 UTC, Chillee commented on model.py
> +    def get_mask(self, kv_len, input_pos) -> BlockMask:
I think we should factor out indexing and support it on BlockMask directly.

2024-08-28 00:17 UTC, Chillee commented on model.py
> +    def _forward(self, mask: BlockMask, idx: Tensor, input_pos: Optional[Tensor] = None) -> Tensor:
> For prefill, we have various length of BlockMask, leading to a dynamic length slicing issue with dynamo.
Why is this a problem? Can't we just index into BlockMask with `input_pos`?

2024-08-28 04:38 UTC, Chillee approved these changes

2024-08-28 04:38 UTC, Chillee commented on model.py
> +    def __init__(self, config: ModelArgs, get_mask_mod: Callable[[int], _mask_mod_signature]) -> None:
`get_mask_mod` shouldn't take an integer - it should take a `mask_mod`. We also don't need to set at as an argument, just set it as an attribute within the module.

2024-08-28 04:38 UTC, Chillee commented on model.py
> +    def __init__(self, config: ModelArgs, get_mask_mod: Callable[[int], _mask_mod_signature]) -> None:
Specifically, you should be able to take any existing `mask_mod` and wrap it to make it automatically support an offset.

2024-08-28 04:38 UTC, Chillee commented on generate.py
> +    mask.mask_mod = model.get_mask_mod(input_pos[0])
I would just automatically transform it here to support an offset.

2024-08-28 04:38 UTC, Chillee requested changes
Mostly looks good (modulo some other nits), although we'll probably want to wait on landing this until the other PRs on pytorch core are landed at least.

2024-08-30 12:37 UTC, merrymercy commented
This looks interesting. I would like to share some numbers we got with torch.compile + flashinfer in sglang. It can serve as some good baselines.

```
# length = 1024
# Decode.  latency: 0.00594 s, throughput:    168.31 token/s
python3 -m sglang.bench_latency --model meta-llama/Llama-2-7b-chat-hf --batch-size 1 --input 1024 --output 8 --enable-torch-compile

# length = 32768
# Decode.  latency: 0.01133 s, throughput:     88.27 token/s
python3 -m sglang.bench_latency --model meta-llama/Llama-2-7b-chat-hf --batch-size 1 --input 1024 --output 8 --enable-torch-compile
```

You can find more numbers at https://github.com/sgl-project/sglang/issues/1008

2024-08-30 20:11 UTC, Chillee commented
@merrymercy We run on nerfed H100s internally at Meta with only 2.4 TB/s of bandwidth, so these numbers aren't 1:1 comparable.

2024-08-30 23:42 UTC, Chillee commented on generate.py
> +    T_buf = roundup(T_new, 128) # round up to multiple of 128 to use flex_attention
Is this still needed?

2024-08-30 23:42 UTC, Chillee commented on generate.py
> +    block_index = input_pos // block_mask.BLOCK_SIZE[0]
Shouldn't we do this divide inside the block mask indexing?

2024-10-21 21:14 UTC, drisspg commented on generate.py
> +    block_mask = create_block_mask(causal_mask, 1, 1, model.max_seq_length, model.max_seq_length, device="cuda")
try doing 
create_block_mask_compile = torch.compile(create_block_mask)

as a global

2024-12-14 01:12 UTC, merged